name: build
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: make PROG=esputil_linux BINDIR=bin CC=musl-gcc CFLAGS="-static -s -Os"
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: make PROG=esputil_macos BINDIR=bin
  windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: make esputil.exe BINDIR=bin
